services:
  fe:
    image: ghcr.io/martin-nef/smart-reviewer:latest-fe
    environment:
      API_URL: "http://127.0.0.1:3000"
    ports:
      - "127.0.0.1:80:80"
  be:
    image: ghcr.io/martin-nef/smart-reviewer:latest-be
    env_file:
      - path: be/.env
        required: false
    environment:
      MONGO_URI: "mongodb://mongo:27017/smart_reviewer"
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:3000:3000"
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - ./tmp/mongo:/data/db
