apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-reviewer-fe
  namespace: smart-reviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-reviewer-fe
  template:
    metadata:
      labels:
        app: smart-reviewer-fe
    spec:
      containers:
        - name: fe
          image: ghcr.io/martin-nef/smart-reviewer:0419966b593b2badd1bec3ba738d8f8f6bfa5496-fe
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "https://smart-reviewer-api.nefcloud.top"
