apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-reviewer

resources:
  - namespace.yaml
  - secrets.yaml
  - deployment-mongo.yaml
  - deployment-fe.yaml
  - deployment-be.yaml
  - service-mongo.yaml
  - service-fe.yaml
  - service-be.yaml
  - ingress-fe.yaml
  - ingress-be.yaml

generatorOptions:
  disableNameSuffixHash: true
