apiVersion: v1
kind: Secret
metadata:
    name: smart-reviewer-secrets
    namespace: smart-reviewer
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:AMTl8MKKmSw=,iv:JF0alAgnidSlcLTCz3tIjv6CAyjdgrFHYL3LgAtDoFk=,tag:2pqgTrqevKIBhT3ypzucEA==,type:str]
    GNEWS_API_KEY: ENC[AES256_GCM,data:f0/1W9nBju8=,iv:vP/KvUIsQfaz0gSYpPHxPgYEloV7wuXVaj5hZR23Mpk=,tag:oYgSlfQFuQqPDlsyDBMiIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGU1NLMHE2Qi9UdS9rQm5Z
            OW9acVRURmNEK1UrODVxWCtDaitoZ1JXNjNZCkFDb2JIMXQ0dVNRNmF0dWpIcW1U
            QXRUVnM2WjdIQ3RHSTJydEN1akcxMlkKLS0tIEt6ZWJSclVZTlFta0ZyZGJ2bTlG
            ajBBVU1Xd1RndUltYmNkcjZPNFRNSUEKOZg7fuDdVWKDHtY9IcwPfYV/P7+sPnKx
            B0DcexBu2cuceo9L1tIeHq/T1R94DWy27ytEKd1nY/4dnTGouOnQ1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age129flpnac62c0cqjhzupx6rkrqe7etjn3jm53zhuu923mt05xluwsy6r9sd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T20:14:36Z"
    mac: ENC[AES256_GCM,data:ZQmiSVGf1gjIsRrvekSl6cz7Pqhq/EiYJD7l6jcQLMPS6xIfkfIKFzab2kPQtpQkKWZNvRPxf6AEvIANdr7XSc0b2rm9drQPSjdihi4Z11ULjvmXI2bJjvNk4tKuzfLoFr2vdJyxzJ/+G7GgrvFyQScXD1bxoZANboyRg2Epg7k=,iv:1Th5RCrtzqoh3Bz5jeq0aggGYSYHrb3wv20weWDbzls=,tag:kozYc9HoYOvTU4sz41792w==,type:str]
    version: 3.13.0
