apiVersion: v1
kind: Secret
metadata:
    name: smart-reviewer-secrets
    namespace: smart-reviewer
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:WnZJwlT4PPJYth1qRxKE0eUkXfWDio6o1un8P4U5+Ppr2HJEJv7mkzh5u55doNrV77tdybbCrL5WU+vISIpIVySjsHpXiXbP+FJrxITGsIcs55Qb3U7CO20EpiADikfape7MMnHeqU+Ybf7NhUx9kgx+Qv/gRF571r3WGIHogCd5252/dhRkPVDabXr2/4wERDa7K5Kip0KeLmWu59z/2lOKgGe89AE=,iv:/O967Q8pfkavxjot26GxXJXYSd94ikkCgPSU42Qkc2M=,tag:O59pa3jBKwmiCVBo5n3sWg==,type:str]
    GNEWS_API_KEY: ENC[AES256_GCM,data:y2QoS9Neyv/XDjNbtGf1dYCtY8HqMcd0oy2V1V//xFU=,iv:hXcf1BfO0CWYZbLchdZZXRxkN2iGn3iPOLMLOgQIPt0=,tag:iQkb6kjoVWVVmqHe7aazDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNG1Wa0RyelR5a0pJWXUz
            YVF1cHhxTmRPMlpsUER5YURoc04wMGRUNGdjCnRVWDYyTEJRTEFzaVRsM1R1aFZk
            UlhsbGxqMWlXYkpSQ1VaYlJySmk1VWMKLS0tIHRIUHUvOFFGL2p5cFVmNlFXZ2lt
            cS9UajM2Skd6Y3J4ZWR3ZDM5M1BlNHcKGjMqtaB6nmF+IyxKUnvPcUVG5aBk2u7Q
            T2yuCf3tjnJx/B8BGLysx8n2ejrxa8K57JBNhKX9CPEm7W+FGK6zDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d8weq7fp7wct6sxvve94hap9v6jz6336txft64t5d5rx39vwwunq8nyjys
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T20:23:58Z"
    mac: ENC[AES256_GCM,data:jt8luO8fB9Ge3MoXjdT9Y0QV1Q0smhd9F8WdZOyJSwW8zsk/Y7qKXhh8bzHJtKiyUWtf+t0gGlviaW+kDVmqoBSx6u6bq+hyfBZtgJsT02UVESfweEz4WPoHtUP+d5yP+RebTkcro35qpGS9znSOGeBBAwiXIUXt0bsZ87QcaeY=,iv:SLzH1U+kZzQ5UxUPY/q7iQLSjTcLOJl/CqhCsFIsW3o=,tag:xTX9vyTI/RWlm9B0oEMEaQ==,type:str]
    version: 3.13.0
