# frozen_string_literal: true

source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.1.3"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
gem "mongoid", "~> 9.0"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:windows, :jruby]

gem "rack-cors"
gem "dotenv-rails"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: [:mri, :windows], require: "debug/prelude"

  # Audits gems for known security defects (use config/bundler-audit.yml to ignore issues)
  gem "bundler-audit", require: false

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  gem "rubocop-shopify", require: false

  gem "rspec-rails", "~> 7.1"
  gem "rspec-sorbet", require: false
  gem "factory_bot_rails"
  gem "tapioca", "0.19.1", require: false
  gem "sorbet", "0.6.13163", require: false
  gem "sorbet-runtime", "0.6.13163", require: false
  gem "sorbet-static-and-runtime", "0.6.13163", require: false
end

group :development do
  gem "ruby-lsp", require: false
  gem "ruby-lsp-rails", require: false
  gem "ruby-lsp-rspec", require: false
end

group :test do
  gem "shoulda-matchers", "~> 6.0"
end
